Repository nanafox/printf, pull requests merged in 2023-10, with the labels that each got.

#54 Added the code logic for handling non-printable characters in string
  handle_string.c
  main.h
Labels: enhancement

#57 Fix task 0 bugs
  printf_helper.c
Labels: bug

#58 Added code to handle task 7
  format_selector.c
  handle_hexadecimals.c
  handle_numbers.c
  main.h
  parse_modifiers.c
  printf_helper.c
Labels: bug, enhancement

#60 Fixed bugs for when number is negative and the zero flag is set
  handle_numbers.c
  main.h
Labels: bug

#61 Custom Printf Update: Improved Formatting with Width Support
  format_selector.c
  handle_char.c
  handle_hexadecimals.c
  handle_numbers.c
  handle_string.c
  handle_width.c
  main.h
  parse_modifiers.c
  printf_helper.c
Labels: enhancement

#63 Bug fixes and code update#61
  format_selector.c
  handle_char.c
  handle_numbers.c
  handle_string.c
  main.h
  parse_modifiers.c
Labels: bug

#65 Add Logic to Handle Precision
  format_selector.c
  handle_hexadecimals.c
  handle_numbers.c
  handle_precision.c
  handle_string.c
  main.h
  parse_modifiers.c
Labels: enhancement

#66 Add Logic to handle Length modifiers
  format_selector.c
  handle_hexadecimals.c
  handle_numbers.c
  main.h
  parse_modifiers.c
Labels: enhancement
